services:
  - type: web
    name: stock-scanner-bot
    env: python
    buildCommand: pip install flask gunicorn requests yfinance pandas
    startCommand: gunicorn app:app
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
